void main(List<String> args) {
  // const myList = [1, 2, 3];
  // myList.add(5);
  // print(myList); // Unhandled exception:

  final myList2 = [1, 2, 3];

  myList2.add(5);
  print(myList2);
}
